# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(829, 409)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("华光行书_CNKI")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 110, 61, 20))
        font = QtGui.QFont()
        font.setFamily("华光行书_CNKI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(180, 150, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华光行书_CNKI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_admin_ID = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_admin_ID.setGeometry(QtCore.QRect(259, 110, 321, 21))
        self.lineEdit_admin_ID.setObjectName("lineEdit_admin_ID")
        self.lineEdit_admin_key = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_admin_key.setGeometry(QtCore.QRect(259, 150, 321, 21))
        self.lineEdit_admin_key.setObjectName("lineEdit_admin_key")
        self.pushButton_admin_enter = QtWidgets.QPushButton(Dialog)
        self.pushButton_admin_enter.setGeometry(QtCore.QRect(360, 240, 93, 28))
        self.pushButton_admin_enter.setObjectName("pushButton_admin_enter")
        self.pushButton_admin_back = QtWidgets.QPushButton(Dialog)
        self.pushButton_admin_back.setGeometry(QtCore.QRect(690, 360, 93, 28))
        self.pushButton_admin_back.setObjectName("pushButton_admin_back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "管理员登录"))
        self.label_2.setText(_translate("Dialog", "账号："))
        self.label_3.setText(_translate("Dialog", "密码："))
        self.pushButton_admin_enter.setText(_translate("Dialog", "登录"))
        self.pushButton_admin_back.setText(_translate("Dialog", "返回"))
