# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(981, 704)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 30, 431, 71))
        font = QtGui.QFont()
        font.setFamily("华光行书_CNKI")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 130, 581, 20))
        font = QtGui.QFont()
        font.setFamily("华光行书_CNKI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lab_face = QtWidgets.QLabel(Dialog)
        self.lab_face.setGeometry(QtCore.QRect(10, 180, 640, 480))
        self.lab_face.setStyleSheet("")
        self.lab_face.setFrameShape(QtWidgets.QFrame.Box)
        self.lab_face.setText("")
        self.lab_face.setObjectName("lab_face")
        self.label_ID = QtWidgets.QLabel(Dialog)
        self.label_ID.setGeometry(QtCore.QRect(741, 300, 171, 20))
        self.label_ID.setStyleSheet("")
        self.label_ID.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ID.setText("")
        self.label_ID.setObjectName("label_ID")
        self.label_name = QtWidgets.QLabel(Dialog)
        self.label_name.setGeometry(QtCore.QRect(741, 360, 171, 20))
        self.label_name.setStyleSheet("")
        self.label_name.setFrameShape(QtWidgets.QFrame.Box)
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")
        self.pushButton_administrators = QtWidgets.QPushButton(Dialog)
        self.pushButton_administrators.setGeometry(QtCore.QRect(730, 460, 141, 28))
        self.pushButton_administrators.setObjectName("pushButton_administrators")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(671, 300, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华光行书_CNKI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(671, 360, 61, 21))
        font = QtGui.QFont()
        font.setFamily("华光行书_CNKI")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "树莓派门禁系统"))
        self.label_2.setText(_translate("Dialog", "小组成员：郑裕丰、马宽宇、李梓墨、王鹏、陈驰昊"))
        self.pushButton_administrators.setText(_translate("Dialog", "管理员点此进入"))
        self.label_3.setText(_translate("Dialog", "学号："))
        self.label_4.setText(_translate("Dialog", "姓名："))
